function [fitresult, gof] = createFitLM_hill(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Mar-2021 11:59:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'Bmax*c^n/(c^n+Kd^n)', 'independent', 'c', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 1 0];
%opts.Lower = [0 0 1];
%opts.Upper= [Inf Inf 1];
%opts.Robust = 'LAR';
opts.StartPoint = [0.964888535199277 0.157613081677548 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




