function [fitresult, gof] = createHillFit5(freeCa2, I)
%CREATEFIT(FREECA2,I)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : freeCa2
%      Y Output: I
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Nov-2020 15:01:02


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( freeCa2, I );

% Set up fittype and options.
ft = fittype( 'Imax*(freeCa2^H)/(EC50^H+freeCa2^H)', 'independent', 'freeCa2', 'dependent', 'I' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );

opts.DiffMaxChange = 0.001;
opts.DiffMinChange = 1e-11;
opts.Display = 'Off';
opts.Lower = [0 1 0];
opts.MaxFunEvals = 10000;
opts.MaxIter = 1000;
opts.Algorithm = 'Trust-Region';%optional
opts.Robust = 'Bisquare';
%opts.Robust = 'LAR';%optional
opts.StartPoint = [0.317099480060861 0.950222048838355 0.0344460805029088];
opts.TolFun = 1e-11;
opts.TolX = 1e-11;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'I vs. freeCa2', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'freeCa2', 'Interpreter', 'none' );
% ylabel( 'I', 'Interpreter', 'none' );
% grid on


